### ISSUE TITLE
Can't Start Server [Pack ver 2.4.2] Error: Could not find or load main class @user_jvm_args.txt

### ISSUE THREAD

**Issue by NicoRaz** [ClaudiusMinimus/Create_Potato_Forge#1]
**Describe the bug**
I can't start server

**To Reproduce**
1. Try to run server
2. see error

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/84834339/148050579-43b39d80-41bb-4497-87e8-5575a5e5b1ba.png)

**Please complete the following information:**
 - Minecraft Version 1.18.1
 - Pack Version  2.4.2
 - not add any mod

**Additional context**

**Logs and Crash Reports**
I don't have any log file because the server never start

**Comment by ClaudiusMinimus** [comment]
I've been sick. Will look into it.

**Comment by ClaudiusMinimus** [comment]
Try opening the file `user_jvm_args.txt` and uncommenting line 9 by removing the hash mark `#`, then try starting the server.
If that does not work, then try removing ` @user_jvm_args.txt` on line 81 of the `start.bat` as shown below:
`%JAVA% "%OTHERARGS%" @libraries/net/minecraftforge/forge/%MINECRAFT%-%FORGE%/win_args.txt nogui %*`

Please let me know if this fixes your issue. if it does, then please let me know which solution worked for you.

Thank you,
CM

**Comment by ClaudiusMinimus** [comment]
The developer who made the Server Pack Creator software I use posted the following:
> Minecraft version 1.18.x requires Java 17. The mentioned error message ... happens when you run the server with a Java installation that does not meet the requirement.

In my reply I asked him:
> Could you do a case check for Java 17 with 1.18.x servers and display a message to the user Java 17 is required?

For the full transcript see: https://github.com/Griefed/ServerPackCreator/issues/171#issuecomment-1007987694

At this point, there is nothing else I can do. I hope my suggestions helped you.
Thank you,
CM
