### ISSUE TITLE
no power generation for refined storage?

### ISSUE THREAD

**Issue by Sh4itan** [ClaudiusMinimus/Create_Potato_Forge#2]
haven't found any item and/or way to generate power for my refined storage setup.

possible workaround/fix:
- add immersive engineering or
- add create crafts & additions

adding one or both mods mentioned above integrates a source of power/way to convert rotation to FE.
i've added immersive engineering to my server and it works fine.

**Comment by ClaudiusMinimus** [comment]
Will be corrected in next release
