### ISSUE TITLE
js not jar

### ISSUE THREAD

**Issue by kur0ta** [ClaudiusMinimus/Create_Potato_Forge#3]
when i download the server pack from the forge page, it works. but when I try to take the server script and put it into my server, i realize thats its a .js file not a .jar. help..?

**Comment by ClaudiusMinimus** [comment]
Did you download the file [create-potato-1.18.1-2.6.0_server.zip](https://www.curseforge.com/minecraft/modpacks/create-on-a-potato/files/3599176)? If so, then you need to extract the zip file and you will see the contents as shown below.

![image](https://user-images.githubusercontent.com/17887664/149435413-6c3f8b9c-5765-4089-8b92-570529b130ef.png)

If you are running Windows, then you need to run the `start.bat`. If Linux or macOS then run the `start.sh` These files will download and install the correct forge server files, and start your world. There is also a README.txt if you run into problems.
