### ISSUE TITLE
2 minimaps and FTBChunks map bugged

### ISSUE THREAD

**Issue by Traktool** [ClaudiusMinimus/Create_Potato_Forge#4]
**Describe the bug**
There is 2 minimaps (Xaero's and FTBChunks) and FTBChunks doesn't show any chunk, also in fullscreen map

**To Reproduce**
1. Start a new World

**Screenshots**
![image](https://user-images.githubusercontent.com/22771674/156917330-2802ebfc-991b-4dcf-a172-4bf4930eaf9e.png)

**Please complete the following information:**
 - Minecraft Version : 1.18.1
 - Pack Version : 2.6.0
 - Have you added any additional mods: Yes
    - OptiFine 1.18.1 HD U H5

**Comment by Traktool** [comment]
I've updated FTBChunks to ftb-chunks-forge-1801.3.3-build.113 instead of ftb-chunks-forge-1801.3.3-build.110 and now it work correctly
But there is still 2 minimaps (imo FTBChunks is better)

**Comment by ClaudiusMinimus** [comment]
FTB Chunks map is supposed to be disabled. To disable open the map settings and disable minimap.

1. Open inventory
2. Click on FTB Chunks map in the top-left corner
3. Click on the gear in the bottom-left corner
4. Under the Minimap section, set Enabled to False

Sorry it took so long, my health took a bit hit this year.
