### ISSUE TITLE
Alex's and Quark Mobs invulnerable

### ISSUE THREAD

**Issue by Ouro130Ros** [ClaudiusMinimus/Create_Potato_Forge#5]
**Describe the bug**
A selection of Quark and Alex's Mobs mobs are invulnerable in both Creative and Survival
Examples include
Alex: Raccoon,  Crocodile
Quark: Foxhound

**To Reproduce**
Try to kill these critters

**Expected behavior**
Dead Critters

**Please complete the following information:**
 - Minecraft Version: 1.18.1
 - Pack Version: [Create Potato 1.18-2.6.0.zip]
 - Have you added any additional mods: N

**Comment by jermoe1** [comment]
I've also encountered this issue with the 1.18-2.6.0 file.

I've found that applying damage with fire for the crocodiles and with a bow for the foxhound works in the meantime.

**Comment by Skytiger220** [comment]
Grissy bear or whatever too

**Comment by ClaudiusMinimus** [comment]
Alex's Mobs were updated in the recent pack update 1.18.2-2.7.1. Alex's Mobs is dropped for 1.19.2 versions of the pack.
Sorry it took so long, my health took a bit hit this year.
