### ISSUE TITLE
CraftPresence menu crash/world corruption

### ISSUE THREAD

**Issue by JadeKaiser** [ClaudiusMinimus/Create_Potato_Forge#7]
**Describe the bug**
CraftPresence(?) breaks the save when you enter its interface.

1. While playing normally, enter the CraftPresence "Config GUI Keybind" interface by pressing the grave ( ` ) key.
2. I have not tried this multiple times, as I did not want to corrupt multiple save files and potentially the entire instance.

Opening the interface in question seems to freeze the game; no cursor was present for me to press any of the buttons available, and pressing various buttons such as the escape key did nothing. The only button that _did_ do something was to press grave again, which crashed the game. Reopening the game and attempting to load the world gives an error message at the end of loading:
Connection Lost
Invalid Player Data

With the only option given being "Back to Server List," which brings me back to the multiplayer server selection screen. (It was a singleplayer world, but that seems to be the default based on my past experiences with world-corrupting crashes.)

 - Minecraft Version 1.18.1
 - Pack Version 2.6.0
 - No additional mods added

**Additional context**
I went to mine andesite, and pressed grave since I wasn't sure if FTB Ultimine or Vein Miner was included in the pack, but figured I should try and see. Clearly, they are not, but breaking the game and corrupting my save is a bit much.

Crash report attached:
[crash-2022-07-06_20.12.45-client.txt](https://github.com/ClaudiusMinimus/Create_Potato_1.18.x/files/9057873/crash-2022-07-06_20.12.45-client.txt)

This is probably an issue on the end of the CraftPresence developer, but it could be due to an interaction between it and some other mod(s) in the pack. I would recommend removing or disabling CraftPresence until the issue is resolved, if it is ever resolved. Even if it's a very low chance of occurring, the severity of the issue is probably unacceptable to you, as it is to me. In lieu of that, perhaps changing some settings to disable the keybind by default would be in order.

**Comment by CDAGaming** [comment]
Apologies for taking so long to address this, v1.8.10 will resolve this issue (Or should)

It was originally fixed in a prototype build 8 months back, but since no-one on the original ticket was able to confirm the fix 100%, I forgot about merging it into a proper build. My bad!

**Comment by CDAGaming** [comment]
Resolved in v1.8.10 (Just released!)

**Comment by ClaudiusMinimus** [comment]
The pack is updated now and should fix this issue.
Sorry it took so long, my health took a bit hit this year.
