### ISSUE TITLE
not really an issue but

### ISSUE THREAD

**Issue by InterstellarSnow** [ClaudiusMinimus/Create_Potato_Forge#8]
do you think you could update the mod pack and update to 1.18.2 so you can update to create 0.5 full steam ahead?

**Comment by hamishpo** [comment]
I Second this!

**Comment by ClaudiusMinimus** [comment]
I have thought about it and would like to. The issue is my heath has taken
a downturn. If I do it then I will not be able to support it without help.

**Comment by ClaudiusMinimus** [comment]
There is also the issue of CF ("Curseforge") changing their API, which has made support of 3rd party launchers challenging. I personally use Linux and CF does not support Linux for Minecraft yet. With that said, I will try to see what I can do.

**Comment by ClaudiusMinimus** [comment]
Done
Sorry it took so long, my health took a bit hit this year.
