### ISSUE TITLE
Instant Crash

### ISSUE THREAD

**Issue by Pyfish1** [ClaudiusMinimus/Create_Potato_Forge#9]
**Describe the bug**
Whenever I start the game, it simply gives up and dies. It creates a blank window then stops. 

**To Reproduce**
1. Start the game on any launcher, I've tried both FTB and MultiMC
2. Wait
3. Game Crashes

**Expected behavior**
The game starting up and being playable

**Screenshots**
N/A

**Please complete the following information:**
 - 1.18.1
 - 2.60
 - No additional mods

**Additional context**

**Logs and Crash Reports**
https://paste.ee/p/GyQyn

**Comment by ClaudiusMinimus** [comment]
Sorry it took so long, my health took a bit hit this year.
The pack was just updated and should fix the issue
